/*
 * Licensed to the Technische Universität Darmstadt under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The Technische Universität Darmstadt
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dkpro.jwpl.tutorial.revisionmachine;

import java.sql.SQLException;
import java.sql.Timestamp;

import org.dkpro.jwpl.api.DatabaseConfiguration;
import org.dkpro.jwpl.api.Page;
import org.dkpro.jwpl.api.WikiConstants;
import org.dkpro.jwpl.api.Wikipedia;
import org.dkpro.jwpl.api.exception.WikiApiException;
import org.dkpro.jwpl.revisionmachine.api.Revision;
import org.dkpro.jwpl.revisionmachine.api.RevisionApi;

/**
 * RevisionMachine Tutorial 6
 * <p>
 * Combines the JWPL {@link Wikipedia} API with the {@link RevisionApi}. If the revision tables
 * were imported into the same database as the JWPL data generated by the DataMachine from the
 * same dump, a page can be looked up by its title and its id used to access its history.
 */
public class T6_PageHistory
    implements WikiConstants
{

    public static void main(String[] args) throws WikiApiException, SQLException
    {
        // configure the database connection parameters
        DatabaseConfiguration dbConfig = new DatabaseConfiguration();
        dbConfig.setHost("SERVER_URL");
        dbConfig.setDatabase("DATABASE");
        dbConfig.setUser("USER");
        dbConfig.setPassword("PASSWORD");
        dbConfig.setLanguage(Language.german);

        Wikipedia wiki = new Wikipedia(dbConfig);
        Page page = wiki.getPage("Hello world");
        int articleId = page.getPageId();

        // the RevisionApi can be created from the same DatabaseConfiguration
        try (RevisionApi revisionApi = new RevisionApi(dbConfig)) {

            Timestamp created = revisionApi.getFirstDateOfAppearance(articleId);
            System.out.println("Page                 : " + page.getTitle());
            System.out.println("Created              : " + created);
            System.out.println("Revisions            : "
                    + revisionApi.getNumberOfRevisions(articleId));

            // the text of the page as it was created
            Revision first = revisionApi.getRevision(articleId, 1);
            System.out.println(first.getRevisionText());
        }
    }
}
