/*
 * Licensed to the Technische Universität Darmstadt under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The Technische Universität Darmstadt
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.dkpro.jwpl.revisionmachine.difftool.consumer.diff.calculation;

import static org.dkpro.jwpl.revisionmachine.difftool.data.codec.RevisionCodecTestSupport.assertDecodes;
import static org.dkpro.jwpl.revisionmachine.difftool.data.codec.RevisionCodecTestSupport.configure;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.dkpro.jwpl.revisionmachine.api.Revision;
import org.dkpro.jwpl.revisionmachine.difftool.data.tasks.content.Diff;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

/**
 * Tests that a full revision without text, as generated by the {@link DiffCalculator} for an empty
 * revision, can be encoded and decoded again.
 */
class DiffCalculatorEmptyRevisionTest
{

    @BeforeAll
    static void setUpConfiguration()
    {
        configure(true);
    }

    @Test
    void emptyFullRevisionCanBeDecoded() throws Exception
    {
        DiffCalculator calculator = new DiffCalculator(null);
        calculator.initNewTask(1);

        Revision revision = new Revision(1);
        revision.setRevisionID(42);
        revision.setRevisionText("");

        Diff diff = calculator.processRevision(revision);
        assertTrue(diff.isFullRevision());

        assertDecodes(diff, diff.getCodecData(), null, "");
    }
}
